In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
dataset = pd.read_csv('Ex09.csv')
feature_columns = ['sepal_length', 'sepal_width', 'petal_length','petal_width']
X = dataset[feature_columns].values
y = dataset['species'].values
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("y_pred    y_test")
for i in range(len(y_pred)):
    print(y_pred[i], "   ", y_test[i])
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

y_pred    y_test
2     2
1     1
0     0
2     2
0     0
2     2
0     0
1     1
1     1
1     1
2     2
1     1
1     1
1     1
2     1
0     0
1     1
1     1
0     0
0     0
2     2
1     1
0     0
0     0
2     2
0     0
0     0
1     1
1     1
0     0
Confusion Matrix:
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
Accuracy of our model is equal 96.67 %.
